// 获取配置及编辑的信息
export const GET_PRICE_INFO = 'GET_PRICE_INFO'
export const CODE_CONFIG = 'CODE_CONFIG'
export const CODE_INFO = 'CODE_INFO'
export const CSRF = 'CSRF'

// 酒店房型有关
export const INIT_HOTEL_ROOMS = 'INIT_HOTEL_ROOMS'
export const INIT_HOTEL_ROOMS_ACTION = 'INIT_HOTEL_ROOMS_ACTION'
export const UPDATE_HOTEL_ROOMS = 'UPDATE_HOTEL_ROOMS'
export const UPDATE_HOTEL_ROOMS_ACTION = 'UPDATE_HOTEL_ROOMS_ACTION'
export const GET_HOTEL_ROOM_BY_CODE_ACTION = 'GET_HOTEL_ROOM_BY_CODE_ACTION'
export const GET_HOTEL_ROOM_BY_CODE = 'GET_HOTEL_ROOM_BY_CODE'
export const CACHE_HOTEL_ROOMS = 'CACHE_HOTEL_ROOMS'

// 关联商品有关
export const GET_HOTEL_GOODS = 'GET_HOTEL_GOODS'
export const GET_HOTEL_GOODS_ACTION = 'GET_HOTEL_GOODS_ACTION'
export const CLEAN_HOTEL_GOODS = 'CLEAN_HOTEL_GOODS'
// 更新单个商品数量
export const UPDATE_HOTEL_NUM = 'UPDATE_HOTEL_NUM'

// 更新步骤
export const UPDATE_PRICE_STEP = 'UPDATE_PRICE_STEP'

// 加载状态
export const UPDATE_LOADING = 'UPDATE_LOADING'
